/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sven_com_apkpatchserver_DiffUtils */

#ifndef _Included_sven_com_apkpatchserver_DiffUtils
#define _Included_sven_com_apkpatchserver_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sven_com_apkpatchserver_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_liu_climb_update_increment_DiffUtils_genDiff
        (JNIEnv *, jclass, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
//extern "C"
//JNIEXPORT jstring JNICALL
//Java_sven_com_apkpatchserver_DiffUtils_genDiff(JNIEnv *env, jclass type, jstring oldApkPath_,
//                                                      jstring newApkPath_, jstring patchPath_) {
//    const char *oldApkPath = env->GetStringUTFChars(oldApkPath_, 0);
//    const char *newApkPath = env->GetStringUTFChars(newApkPath_, 0);
//    const char *patchPath = env->GetStringUTFChars(patchPath_, 0);
//
//    // TODO
//
//    env->ReleaseStringUTFChars(oldApkPath_, oldApkPath);
//    env->ReleaseStringUTFChars(newApkPath_, newApkPath);
//    env->ReleaseStringUTFChars(patchPath_, patchPath);
//
//    return env->NewStringUTF(returnValue);
//}