/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sven_com_apkpatchserver_PatchUtils */

#ifndef _Included_sven_com_apkpatchserver_PatchUtils
#define _Included_sven_com_apkpatchserver_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sven_com_apkpatchserver_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liu_climb_update_increment_PatchUtils_patch
        (JNIEnv *, jclass, jstring, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_liu_climb_update_increment_PatchUtils_patch2
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
